# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- checkout: none
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    git clone https://github.com/taylordevereaux/sql-tools.git
    git checkout master
  displayName: 'git checkout'

- script: |
    npm install -g @angular/cli
    npm install -g angular-cli-ghpages
    npm install
    ng build --prod --base-href "https://taylordevereaux.github.io/sql-tools/"
  displayName: 'npm install and build'


- script: |
    npx angular-cli-ghpages --dir=dist/sql-tools --no-silent
  displayName: 'npx github pages deploy'
